baseURL = "https://g-boulanger.com/"
title = "Guillaume Boulanger"
theme = "PaperMod"
languageCode = "en-us"
enableRobotsTXT = true

[params]
  author = "Guillaume Boulanger"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2