baseURL = "https://slowfwd.fr/"
title = "Slowly Forward"
description = "Thoughts on philosophy, data, endurance and the self."
keywords = ["philosophy", "data", "triathlon", "introspection", "free will"]
languageCode = "en-us"
enableRobotsTXT = true
enableGitInfo = true

[[module.imports]]
  path = "github.com/imfing/hextra"

# Performance optimizations
minify = true
# disableKinds = ["taxonomy", "term"] # Re-enabled for better SEO

# Image processing
[imaging]
  quality = 85
  resampleFilter = "Lanczos"

# SEO and meta tags
[params]
  author = "Guillaume Boulanger"
  authorURL = "https://slowfwd.fr/"
  defaultTheme = "auto"
  
  # SEO settings
  [params.seo]
    googleAnalytics = "G-0D56MFYPPL"
    googleSiteVerification = ""
    baiduSiteVerification = ""
    yandexSiteVerification = ""
    bingSiteVerification = ""
    
  # Open Graph
  [params.openGraph]
    image = "static/images/g-boulanger.jpeg"
    imageWidth = 1200
    imageHeight = 630
    
  # Reading time
  [params.readingTime]
    enabled = true
    wordsPerMinute = 200
    
  [params.navbar]
  displayTitle = true
  displayLogo = false
  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

    [params.navbar.logo]
    path = "images/cycles.png"
    dark = "images/cycles.png"
    link = "/"
    width = 40
    height = 20

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    noClasses = false
    style = "github"
    lineNos = true
    lineNumbersInTable = true
    noHl = false
    hlLines = ""
    hlInverse = false

# Google Analytics
[services.googleAnalytics]
ID = "G-0D56MFYPPL"

# Menu configuration
[menu]
  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Search"
  weight = 3

  [menu.main.params]
    type = "search"

# Taxonomies for better content organization
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Output formats
[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"
    isPlainText = true
    notAlternative = true

# Sitemap configuration
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Security headers
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.http]
    methods = ['(?i)GET|POST|HEAD']
    schemes = ['(?i)HTTP|HTTPS']
    urlRegexp = '.*'
