baseURL = "https://slowfwd.fr/"
title = "Slowly Forward"
languageCode = "en-us"
enableRobotsTXT = true

[[module.imports]]
  path = "github.com/imfing/hextra"

[params]
  author = "Guillaume Boulanger"
  [params.navbar]
  displayTitle = true
  displayLogo = false

    [params.navbar.logo]
    path = "images/cycles.png"
    dark = "images/cycles.png"
    link = "/"
    width = 40
    height = 20

[menu]
  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

  [[menu.main]]
  name = "Documentation"
  url = "/docs/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

  [[menu.main]]
  name = "Search"
  weight = 4

  [menu.main.params]
    type = "search"